feat: Add initial configuration
lablabs/kyverno-policies pull request #1
Opened 2023-04-27 05:43 UTC by Balsir

2023-05-12 11:21 UTC, dojci requested changes

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/values.yaml
> +validationFailureActionOverrides: []
Please add comment example for `validationFailureActionOverrides`

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/templates/podSecurityBaseline/disallowHostNamespaces.yaml
> +{{- if and (or $policyValues.enabled $categoryValues.enabled .Values.enableAll) (not (or $policyValues.disabled $categoryValues.disabled)) }}
Using `enabled` and `disabled` flags is very confusing. We should use only one controlling flag `enabled`, please update default values and change conditionals.

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/templates/podSecurityBaseline/disallowHostNamespaces.yaml
> +{{- if and (or $policyValues.enabled $categoryValues.enabled .Values.enableAll) (not (or $policyValues.disabled $categoryValues.disabled)) }}
Another thing is that we could put things that are used almost everywhere in the temple function (tpl) with simple reference in code base to keep DRY principle and future updates/changes. This comment is related to the multiple sections and not only to enabled/disabled conditionals. We should put most of the heavy lifting to the templates in this case.

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/ci/enable-all-values.yaml
I would rather move CI test definition from the core chart. Please see the reorg comment.

2023-05-12 11:21 UTC, dojci commented on README.md
We had short discussions in the office about directory structure and two README files, and we came to the opinion that it would be better to have content of 'charts/kyevrno-policies' directly in the root directory instead of using multiple directory levels because this helm chart repo is the single purpose repo and we don't want to have multiple helm chart definition in it + we will have only one README.

2023-05-12 11:21 UTC, dojci commented on .pre-commit-config.yaml
> +      - id: detect-private-key
Do we need this type of check?

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/Chart.yaml
> +appVersion: "0.1.0"
I don't think that this variable is necessary in our use-case

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/Chart.yaml
> +version: 0.1.0
This should always be auto-updated after with new release.

2023-05-12 11:21 UTC, dojci commented on charts/kyverno-policies/README.md
TODO @dojci: review readme after requested changes

2023-05-12 11:21 UTC, dojci commented on .github/workflows/helm-lint-test.yaml
@MonolithProjects plz review workflow

2023-05-12 11:21 UTC, dojci commented on .github/workflows/helm-release.yaml
@MonolithProjects plz review workflow

2023-05-12 11:43 UTC, Balsir commented on charts/kyverno-policies/templates/podSecurityBaseline/disallowHostNamespaces.yaml
> +{{- if and (or $policyValues.enabled $categoryValues.enabled .Values.enableAll) (not (or $policyValues.disabled $categoryValues.disabled)) }}
The reason for using separate `enabled` and `disabled` flags is that we are using categories that you can enable. There may be a use case where you want to enable the entire category except for one policy. Ideally, you would set it by setting `enabled=false` for the specific policy. Unfortunately, Helm doesn't work well with boolean values (`false` is treated as `null` and vice versa), not allowing this kind of control via one variable.

Without the `disabled` flag, you need to specifically enable each and every chart that you want to enable just so you can disable one, taking away the convenience of categories. If we don't build any functionality around categories (and have them purely as visual aids), and enabling/disabling of policies will be managed only on policy level, I'm fine with removing `disabled`. Otherwise, if there is no alternative to simplify this configuration, I would prefer to keep it.

EDIT: Another option is make `enabled` a string with values ("yes", "no", null), which would work, but feels like an antipattern (true/false vs "yes"/"no"). I am open to suggestions.

2023-05-12 11:54 UTC, Balsir commented on charts/kyverno-policies/ci/enable-all-values.yaml
The folder location is standard for chart testing tool that runs in github actions.
https://github.com/helm/chart-testing/blob/main/doc/ct_install.md

2023-05-12 11:58 UTC, Balsir commented on charts/kyverno-policies/Chart.yaml
> +appVersion: "0.1.0"
will check

2023-05-12 12:00 UTC, Balsir commented on charts/kyverno-policies/Chart.yaml
> +version: 0.1.0
This gets updated via a feature request - main contains the current released version. Chart testing lint gh action checks if the version is changed in the PR.

2023-05-12 12:01 UTC, Balsir commented on .pre-commit-config.yaml
> +      - id: detect-private-key
Taken straight out of addon-template. 
If you want the check gone, I can remove it.

2023-05-12 12:17 UTC, Balsir commented on README.md
This doesn't seem to be standard practice, no matter if you are maintaining one or multiple charts.
The helm chart should be in a charts folder.

Regarding README, I've been trying to generate it via helm-docs. Artifacthub also pulls info from the chart README (because it's part of the release).
My workaround would look like this https://github.com/lablabs/helm-chart-template/tree/feat/template-setup
1. Top level README - banner, contribution, **link to chart README**, maaaybe installation guide, license....
2. Chart details, values, the whole documentation, generated from README.md.gotmpl by helm-docs

Any suggestions are welcome.

2023-05-12 12:29 UTC, Balsir commented on charts/kyverno-policies/templates/podSecurityBaseline/disallowHostNamespaces.yaml
> +{{- if and (or $policyValues.enabled $categoryValues.enabled .Values.enableAll) (not (or $policyValues.disabled $categoryValues.disabled)) }}
> Another thing is that we could put things that are used almost everywhere in the temple function (tpl) with simple reference in code base to keep DRY principle and future updates/changes. This comment is related to the multiple sections and not only to enabled/disabled conditionals. We should put most of the heavy lifting to the templates in this case.

Good point. DRY principle could mainly be applied to the settings section, which is homogeneous for most policies - question is how we would deal with exceptions.

I would like to release the chart as-is, test it, and add DRY in the next release.

2023-05-12 12:48 UTC, Balsir commented on charts/kyverno-policies/values.yaml
> +validationFailureActionOverrides: []
Done

2023-05-12 17:46 UTC, Balsir commented on charts/kyverno-policies/ci/enable-all-values.yaml
Agreed to stay as was

2023-05-12 17:46 UTC, Balsir commented on README.md
Workaround accepted during call ;)

2023-05-12 17:47 UTC, Balsir commented on .pre-commit-config.yaml
> +      - id: detect-private-key
Stays as-is for now

2023-05-15 06:43 UTC, dojci approved these changes
LGTM, @MonolithProjects please review GitHub workflows outside of this PR

2023-05-15 07:29 UTC, merged

2023-05-16 08:38 UTC, MonolithProjects commented on .github/workflows/helm-lint-test.yaml
> +    runs-on: ubuntu-latest
we should pin the runner to `ubuntu-22.04`

2023-05-16 08:38 UTC, MonolithProjects commented on .github/workflows/helm-lint-test.yaml
> +    runs-on: ubuntu-20.04
we should pin the runner to ubuntu-22.04

2023-05-16 08:38 UTC, MonolithProjects commented on .github/workflows/helm-lint-test.yaml
> +          python-version: '3.9'
i guess we could use newer python version

2023-05-16 08:38 UTC, MonolithProjects commented on .github/workflows/helm-lint-test.yaml
> +        uses: helm/kind-action@v1.5.0
there is already kind-action v1.6.0 (released just few minutes ago) :smile:

2023-05-16 08:38 UTC, MonolithProjects commented on .github/CONTRIBUTING.md
> +1. Update the README.md with details of changes including example hcl blocks and [example files](./examples) if appropriate.
this point can be removed as the contributor does not need to edit the main README.md file in the root directory and the README.md in the charts dir will be updated automatically by pre-commit/helm-docs

2023-05-16 08:38 UTC, MonolithProjects commented on .github/CONTRIBUTING.md
> +- [ ] README.md has been updated after any changes. The variables and outputs in the README.md has been generated (using the `terraform_docs` pre-commit hook).
terraform-docs > helm-docs

2023-05-16 08:38 UTC, MonolithProjects commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +    label: Terraform Version
label, description and placeholder in this template should be adjusted to a bug for helm chart